baseURL = "/"
defaultContentLanguage = "en"
title = "Spin Demo"
theme = "spin"
themesDir = "../.."
enableRobotsTXT = true

[languages]
  [languages.en]
    label = "English"
    locale = "en-us"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  collection = "collections"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "catppuccin-mocha"

[params]
  author = "AlecGhost"
  brand = "AlecGhost/Spin"
  description = "A minimalist, dark-themed Hugo module demo."
  standaloneSection = "notes"
  github = "https://github.com/AlecGhost/spin"
